locking papermill to 2.2.0 b/c of a inspect bug
TODO: need to figure out how to fix it

```
 nb_params = papermill.inspect_notebook(nb_name)
 File "***/***/lib/python3.6/site-packages/papermill/inspection.py", line 120, in inspect_notebook
  nb = _open_notebook(notebook_path, parameters)
 File "***/***/lib/python3.6/site-packages/papermill/inspection.py", line 19, in _open_notebook
  return load_notebook_node(input_path)
 File "***/***/lib/python3.6/site-packages/papermill/iorw.py", line 411, in load_notebook_node
  nb_upgraded = nbformat.v4.upgrade(nb)
 File "***/***/lib/python3.6/site-packages/nbformat/v4/convert.py", line 39, in upgrade
  _warn_if_invalid(nb, from_version)
 File "***/***/lib/python3.6/site-packages/nbformat/v4/convert.py", line 21, in _warn_if_invalid
  validate(nb, version=version)
 File "***/***/lib/python3.6/site-packages/nbformat/validator.py", line 262, in validate
  relax_add_props=relax_add_props):
 File "***/***/lib/python3.6/site-packages/nbformat/validator.py", line 284, in iter_validate
  validator = get_validator(version, version_minor, relax_add_props=relax_add_props)
 File "***/***/lib/python3.6/site-packages/nbformat/validator.py", line 56, in get_validator
  schema_json = _get_schema_json(v, version=version, version_minor=version_minor)
 File "***/***/lib/python3.6/site-packages/nbformat/validator.py", line 90, in _get_schema_json
  schema_path = os.path.join(os.path.dirname(v.__file__), v.nbformat_schema[(None, None)])
KeyError: (None, None)
```